Fix XML parse error
On Ubuntu 20.04 with librsvg 2.48.0 the activity hangs and logs contain;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Dimensions.activity/game.py", line 514, in _prepare_new_game
    self.deck.create(self._sprites, self.card_type,
  File "/usr/share/sugar/activities/Dimensions.activity/deck.py", line 85, in create
    i = self._make(sprites, card_type, numbers_type, i,
  File "/usr/share/sugar/activities/Dimensions.activity/deck.py", line 138, in _make
    self.cards[i].create(
  File "/usr/share/sugar/activities/Dimensions.activity/card.py", line 45, in create
    self.spr = Sprite(sprites, 0, 0, svg_str_to_pixbuf(string, True))
  File "/usr/share/sugar/activities/Dimensions.activity/card.py", line 69, in svg_str_to_pixbuf
    pl.close()
gi.repository.GLib.Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):25:2: Namespace prefix xlink for href on image is not defined

librsvg 2.47.0 introduced stricter namespaces in the XML parser,
https://gitlab.gnome.org/GNOME/librsvg/-/blob/master/NEWS#L67

so add namespace declarations.